/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package broom;

import java.sql.DriverManager;
import java.sql.*;
/**
 *
 * @author maysh
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
    }
    
    
    ResultSet rs= null;
    
    String nname;

    public Student(String name) {
        
        initComponents();
       txttname.setText(name);
        
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txttcharms = new javax.swing.JTextField();
        txtthistory = new javax.swing.JTextField();
        txtttrans = new javax.swing.JTextField();
        txttastronomy = new javax.swing.JTextField();
        txttpotions = new javax.swing.JTextField();
        txttarts = new javax.swing.JTextField();
        txttcomment = new javax.swing.JTextField();
        txttname = new javax.swing.JTextField();
        txttyear = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Year");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Charms");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("History Of Magic");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 230, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Transfiguration");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("Astronomy ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 270, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("Potions");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setText(" Dark Arts");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 30));

        jLabel9.setFont(new java.awt.Font("Vladimir Script", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 51));
        jLabel9.setText("Comment Box");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 250, 50));

        jLabel10.setFont(new java.awt.Font("Vladimir Script", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Course Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 40));

        txttcharms.setBackground(new java.awt.Color(255, 255, 204));
        txttcharms.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        txttcharms.setForeground(new java.awt.Color(102, 0, 51));
        txttcharms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttcharmsActionPerformed(evt);
            }
        });
        getContentPane().add(txttcharms, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 150, 30));

        txtthistory.setBackground(new java.awt.Color(255, 255, 204));
        txtthistory.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        txtthistory.setForeground(new java.awt.Color(102, 0, 51));
        txtthistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtthistoryActionPerformed(evt);
            }
        });
        getContentPane().add(txtthistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 242, 150, 30));

        txtttrans.setBackground(new java.awt.Color(255, 255, 204));
        txtttrans.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        txtttrans.setForeground(new java.awt.Color(102, 0, 51));
        txtttrans.setCaretColor(new java.awt.Color(102, 0, 51));
        txtttrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtttransActionPerformed(evt);
            }
        });
        getContentPane().add(txtttrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 282, 150, 30));

        txttastronomy.setBackground(new java.awt.Color(255, 255, 204));
        txttastronomy.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        txttastronomy.setForeground(new java.awt.Color(102, 0, 51));
        getContentPane().add(txttastronomy, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 322, 150, 30));

        txttpotions.setBackground(new java.awt.Color(255, 255, 204));
        txttpotions.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        txttpotions.setForeground(new java.awt.Color(102, 0, 51));
        getContentPane().add(txttpotions, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 210, 30));

        txttarts.setBackground(new java.awt.Color(255, 255, 204));
        txttarts.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        txttarts.setForeground(new java.awt.Color(102, 0, 51));
        txttarts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttartsActionPerformed(evt);
            }
        });
        getContentPane().add(txttarts, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 210, 30));

        txttcomment.setBackground(new java.awt.Color(153, 51, 0));
        txttcomment.setFont(new java.awt.Font("Vladimir Script", 1, 36)); // NOI18N
        txttcomment.setForeground(new java.awt.Color(255, 255, 255));
        txttcomment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttcommentActionPerformed(evt);
            }
        });
        getContentPane().add(txttcomment, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 220, 120));

        txttname.setBackground(new java.awt.Color(255, 255, 204));
        txttname.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        txttname.setForeground(new java.awt.Color(102, 0, 51));
        txttname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttnameActionPerformed(evt);
            }
        });
        getContentPane().add(txttname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 150, 30));

        txttyear.setBackground(new java.awt.Color(255, 255, 204));
        txttyear.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        txttyear.setForeground(new java.awt.Color(102, 0, 51));
        txttyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttyearActionPerformed(evt);
            }
        });
        getContentPane().add(txttyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 150, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/broom/history-ppt-joseph-powerpoint-template-7.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttcommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttcommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttcommentActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        String name= txttname.getText();
        System.out.println(name);
        studentt s = new studentt();
        String n= s.getName();
        
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
             System.out.println("successful 1");
     
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/hogwarts","root","Maysha4567@4");
           Statement st= con.createStatement();
         // rs= st.executeQuery("select*from magic inner join marks where magic.name='"+name+"' and marks.name(name");
         rs= st.executeQuery("select*from marks where name= '"+name+"'");
         // rs= st.executeQuery("select*from marks ");
           if(rs.next()) 
           {
               
             txttname.setText(rs.getString(1))   ;
            txttyear.setText(rs.getString(2))   ;
            txttcharms.setText(rs.getString(3))   ;
            txtthistory.setText(rs.getString(4))   ;
            txtttrans.setText(rs.getString(5))   ;
            txttastronomy.setText(rs.getString(6))   ;
            txttpotions.setText(rs.getString(7))   ;
            txttarts.setText(rs.getString(8))   ;
            //txttname.setText(rs.getString(9))   ;
              txttyear.setText(rs.getString(10))   ;
            txttcomment.setText(rs.getString(9))   ;
            
            
            
            
            
            
            
            
            
            
            
            
            
           }
            
            
            
        }catch(Exception e){
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_formComponentShown

    private void txttyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttyearActionPerformed

    private void txttartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttartsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttartsActionPerformed

    private void txttnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttnameActionPerformed

    private void txttcharmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttcharmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttcharmsActionPerformed

    private void txtthistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtthistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtthistoryActionPerformed

    private void txtttransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtttransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtttransActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txttarts;
    private javax.swing.JTextField txttastronomy;
    private javax.swing.JTextField txttcharms;
    private javax.swing.JTextField txttcomment;
    private javax.swing.JTextField txtthistory;
    private javax.swing.JTextField txttname;
    private javax.swing.JTextField txttpotions;
    private javax.swing.JTextField txtttrans;
    private javax.swing.JTextField txttyear;
    // End of variables declaration//GEN-END:variables
}
